#Author: Siddhartha V
version: "3"
services:
  springBootApp:
    image: sidvps1007/api:1.1
    container_name: dockerproject
    environment:
      -   POSTGRES_HOST=dockerprojectdb
      -   SERVER_PORT=9013
      -   SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDb:5432/postgres
      -   SPRING_DATASOURCE_USERNAME=postgres
      -   SPRING_DATASOURCE_PASSWORD=10072001
      -   SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      -   SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9000:9013"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure
  postgresDb:
    image: 'postgres:13.1-alpine'
    container_name: dockerprojectdb
    ports:
      - "5432:5432"
    networks:
     - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      -   POSTGRES_USER=postgres
      -   POSTGRES_PASSWORD=10072001
      -   POSTGRESDB=postgres
networks:
  network:
volumes:
  volume: